food/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as V
urlpatterns = ( [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('cart/', V.cart, name='cart'),

    path('search/', V.search, name="search"),
    path('checkout/', V.checkout, name="checkout"),
    path('orders/', include('orders.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point
# Create your models here.
class userManager(BaseUserManager):
    def create_user(self, firstname, lastname, username, email, password=None):
        if not email:
            raise ValueError("email required...")
        if not username:
            raise ValueError("username required...")
        user = self.model(
            username = username,
            firstname = firstname,
            lastname = lastname,
            email = self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, firstname, lastname, username, email, password=None):
        user = self.create_user(
            username = username,
            firstname = firstname,
            lastname = lastname,
            password = password,
            email = self.normalize_email(email)
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user
    
class User(AbstractBaseUser):
    customer = 1
    Vendor = 2
    role_choices = (
        (customer, "customer"),
        (Vendor, "restaurant"),
    )

    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    role = models.PositiveSmallIntegerField(choices=role_choices, default=1)
    
    date_joined = models.DateTimeField(auto_now_add=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'firstname', 'lastname']
    objects = userManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    
class userProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='users/profile_pics', blank=True, null=True)
    address = models.CharField(max_length=300,blank=True, null=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.user.username
  
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
        return super(userProfile, self).save(*args, **kwargs)

orders/models.py
from django.db import models
import simplejson
from accounts.models import User, userProfile
from menu.models import foodItem

# Create your models here.
class Payment(models.Model):
    PAYMENT_METHOD = (
        ('RazorPay', 'RazorPay'),
        ('PayPal', 'PayPal'),
    )
    PAYMENT_STATUS =  (
        ('Pending', 'Pending'),
        ('Paid', 'Paid'),
        ('Cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=50, unique=True)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=15)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    status = models.CharField(max_length=15, choices=PAYMENT_STATUS, default="Pending") 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.transaction_id
    
class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.OneToOneField(Payment, on_delete=models.SET_NULL, related_name='order', blank=True, null=True)
    order_number = models.CharField(max_length=25, unique=True)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=25, blank=True)
    state = models.CharField(max_length=25, blank=True)
    city = models.CharField(max_length=30)
    pincode = models.CharField(max_length=12)
    total = models.DecimalField(max_digits=8, decimal_places=2)
    tax_data = models.JSONField(blank=True, help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}")
    total_tax = models.DecimalField(max_digits=8, decimal_places=2)
    vendor_data = models.JSONField(blank=True, null=True, help_text="Data format: {'vendor_id': {'subtotal': subtotal, 'tax_total': tax_total, 'total': total, 'tax_dict': {'tax_type': {'tax_percentage': percentage, 'tax_amount': amount}}}}")
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def name(self):
        return f'{self.firstname} {self.lastname}'
    
    def get_vendor_data(self, vendor):
        vendor_data = simplejson.loads(self.vendor_data).get(str(vendor.id), None)
        order_info = {
            'order_number': self.order_number,
            'status': self.status,
            'date': self.created_at,
            'subtotal': vendor_data['subtotal'],
            'tax_total': vendor_data['tax_total'],
            'total': vendor_data['total'],
            'tax_breakdown': vendor_data['tax_dict'],
        }

    
    def __str__(self):
        return self.order_number
    
class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    fooditem = models.ForeignKey(foodItem, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_name
    
    
    

accounts/forms.py
from django import forms
from .models import *

class userForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("firstname", "lastname", "username", "email",  "password",)

    def clean(self):
        cleaned_data = super(userForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if not password or not confirm_password:
            raise forms.ValidationError("Password must not be empty")
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match")

class userProfileForm(forms.ModelForm):
    address=forms.CharField(widget=forms.TextInput(attrs={"required":"required", "placeholder":"start typing..."}))
    profile_pic=forms.ImageField(widget=forms.FileInput(attrs={"class":"btn-btn-info"}))
    #one way to make field readonly
    latitude=forms.CharField(widget=forms.TextInput(attrs={"readonly":"readonly"}))
    
    class Meta:
        model = userProfile
        fields = ["profile_pic", "address", "country", "state", "city", "pincode","latitude", "longitude",]
    #over-ridding method for making field readonly
    def __init__(self, *args, **kwargs):
        super(userProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field=='longitude':
                self.fields[field].widget.attrs['readonly']='readonly'


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('firstname', 'lastname')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>khanamangao</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static "/css/iconmoon.css" %}" rel="stylesheet">
	<link href="{% static "/css/style.css" %}" rel="stylesheet">
	<link href="{% static "/css/custom.css" %}" rel="stylesheet">
	<link href="{% static "/css/cs-foodbakery-plugin.css" %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static "/css/bootstrap-slider.css" %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css">

	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static "/js/modernizr.js" %}"></script>
	<script src="{% static "/js/bootstrap.js" %}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="{% static '/js/custom.js' %}"></script>
	<script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>

	<script>
		$(document).ready( function(){
			$('#OrdersPaginationTable').DataTable();
		})
	</script>

	{% if 'profile/' in request.path or request.path == '/' %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" defer></script>
	{% endif %}
	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>
	<!--Main Wrapper-->
	<div class="wrapper">
		<!-- Header Start -->
		{% include "headbar.html" %}
		<!-- Header End -->
        {% block content %}

        {% endblock content %}
		<!-- Footer Start -->
		<footer id="footer" class="footer-style-2">
			<div class="footer-widget">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="widget widget-newsletter">
								<div class="widget-title">
									<h5>Subscribe to our Newsletter</h5>
								</div>
								<div class="fieldset">
									<form action="#">
										<div class="field-holder">
											<label>
												<i class=" icon-envelope3"></i>
												<input type="text" class="field-input" placeholder=" Enter Your Email Address...">
											</label>
										</div>
										<div class="field-holder btn-holder">
											<input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright-sec">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="copyright-inner">
								<div class="copy-right">
									<p>© 2020 Foodbakery. All Rights Reserved. Developed By <a href="#">Rathan Kumar</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /.cs-copyright -->
		</footer>
		<!-- Footer End -->
	</div>
	
	<!-- Modal Popup End -->
	<script src="{% static "/js/scripts.js" %}"></script>
	<script src="{% static "/js/functions.js" %}"></script><script src="{% static "/js/scripts.js" %}"></script>
	<script src="{% static "/js/functions.js" %}"></script>
</body>

</html>

templates/headbar.html
{% load static %}
<header id="header">
    <div class="main-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="logo">
                        <figure>
                            <a href="{% url "home" %}" class="light-logo">
                                <img src="{% static "/logo/khanamangao.png" %}" alt="FoodBakery" width="100%">
                            </a>
                        </figure>
                    </div>
                    <div class="main-location">
                        <ul>
                            <li class="location-has-children choose-location">
                                <form action="{% url "home" %}">
                                    {% if location %}
                                    <input type="text" value="{{ location }}" id="id_location" name="location" placeholder="Your current location" autocomplete="off">
                                    <input type="hidden" value="{{ lat }}" id="id_latitude1" name="lat">
                                    <input type="hidden" value="{{ long }}" id="id_longitude1" name="long">
                                    {% else %}
                                    <input type="text" value="" id="id_location" name="location" placeholder="Your location" autocomplete="off">
                                    <input type="hidden" value="" id="id_latitude1" name="lat">
                                    <input type="hidden" value="" id="id_longitude1" name="long">
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                    <span id="foodbakery_radius_location_open" onclick="getLocation()" class="foodbakery-radius-location">
                                        <i class="icon-target5"></i>
                                    </span>
                                    {% else %}
                                    <span id="foodbakery_radius_location_open" onclick="" class="foodbakery-radius-location">
                                        <i class="icon-target5"></i>
                                    </span>
                                    {% endif %}
                                </form>
                                
                            </li>
                        </ul>
                        </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="login-option">
                        {% if user.is_authenticated and user.role == 1%}
                        <a href="{% url "cart" %}">
                            <i class="fa fa-shopping-cart text-danger" style="font-size:25px;"></i>
                            <span class="badge badge-warning" id="cart_counter" style="border-radius:50px; position:relative; bottom:10px; left:-5px;">{{cart_count}}</span>
                        </a>
                        {% endif %}
                        <a href="{% url "marketplace"%}"  class="btn btn-outline-danger text-uppercase font-weight-bold">Marketplace</a>
                        {% if user.is_authenticated %}
                        <a class="cs-color cs-popup-joinus-btn login-popup"  href="{% url 'myAccount' %}" style="margin-left: 0;">My account</a> |
                        <a class="cs-color cs-popup-joinus-btn login-popup text-danger"  href="{% url "logout" %}" style="margin-left: 0;">
                            Logout </a> 
                        {% else %}
                        <a class="cs-color cs-popup-joinus-btn login-popup"  href="{% url "login" %}" style="margin-left: 0;">
                            Login </a> /
                        <a class="cs-color cs-popup-joinus-btn login-popup" href="{% url "registerUser" %}" style="margin-left: 0;">
                            Register
                        </a> 
                        
                        <a class="get-start-btn" href="{% url "registerVendor" %}">
                            Register
                            Restaurant
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<script>
    var x = document.getElementById("id_location");
    var latField = document.getElementById("id_latitude1");
    var longField = document.getElementById("id_longitude1");

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            x.placeholder = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        var lat = position.coords.latitude;
        var long = position.coords.longitude;
        var url = "https://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + long + "&key={{ GOOGLE_API_KEY }}";

        $.ajax({
            url: url,
            type: "GET",
            success: function (response) {
                if (response.results && response.results[0]) {
                    var location = response.results[0].formatted_address;
                    x.value = location;
                    latField.value = lat;
                    longField.value = long;

                    // Update session or backend
                    $.ajax({
                        url: "{% url 'home' %}",
                        type: "GET",
                        data: { location: location, lat: lat, long: long },
                        success: function () {
                            window.location.href = '/';
                        },
                        error: function (xhr, status, error) {
                            console.error("Error storing location data in session:", error);
                        }
                    });
                } else {
                    console.error("No results found for geolocation");
                }
            },
            error: function (xhr, status, error) {
                console.error("Error fetching location data:", error);
            }
        });
    }
</script>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin main-search-bar" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static "/extra-images/bg-image1.jpg" %}) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<form action="{% url "search" %}" method="GET">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
											<div class="field-holder">
												<input type="text" name="keyword" placeholder="Restaurant/Food name">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
															{% if location %}
															<input type="text" name="address" class="location-field-text filter" id="id_address" value="{{ location }}" required placeholder="All Locations">
															<input type="hidden" name="lat" value="{{ lat }}" id="id_latitude">
															<input type="hidden" name="long" value="{{ long }}" id="id_longitude">
															{% else %}
															<input type="text" name="address" class="location-field-text filter" id="id_address" value="" required placeholder="All Locations">
															<input type="hidden" name="lat" value="" id="id_latitude">
															<input type="hidden" name="long" value="" id="id_longitude">
															{% endif %}
														</div>
													</li>
												</ul>
											</div>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<select name="radius" id="radius" required style="height:50px">
												<option value="" selected>Choose radius</option>
												<option value="5">5km</option>
												<option value="15">15km</option>
												<option value="25">25km</option>
												<option value="40">40km</option>
												<option value="50">50km</option>
												<option value="75">75km</option>
												<option value="100">100km</option>
											</select>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<div class="field-holder">
												<input type="submit" value="Search" style="font-size:12px">
											</div>
										</div>
									</div>
								</form>
								
							</div>
						</div>
						
					</div>
				</div>
			</div>
			<!-- Main Search End -->
			
			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Nearest Restaurants</h2>
								<p>Explore restaurants near to your locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right: 0 !important; padding-left: 0 !important;">
							<div class="company-logo">
								<ul>	
									{% for vendor in vendors %}
									<li class="has-border">
										<figure>
											{% if vendor.vendor_profile.profile_pic %}
											<a href="{% url "vendor_detail" vendor.slug %}"><img src="{{vendor.vendor_profile.profile_pic.url}}" class="attachment-full size-full wp-post-image" width="220px" height="125px" alt=""></a>
											{% else %}
											<a href="{% url "vendor_detail" vendor.slug %}"><img src="{% static "images/default-profile.png" %}" class="attachment-full size-full wp-post-image" width="220px" height="125px" alt=""></a>
											{% endif %}
										</figure>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									{% for vendor in vendors %}
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure>
													{% if vendor.vendor_profile.profile_pic %}
													<a href="{% url "vendor_detail" vendor.slug %}"><img src="{{vendor.vendor_profile.profile_pic.url}}" class="img-thumb wp-post-image" alt="">
													</a>
													{% else %}
													<a href="{% url "vendor_detail" vendor.slug %}"><img src="{% static "images/default-profile.png" %}" class="img-thumb wp-post-image" alt="">
													</a>
													{% endif %}
												</figure>
											</div>
											<div class="text-holder">
												<div class="post-title">
													<h5>
														<a href="{% url "vendor_detail" vendor.slug %}">{{vendor.vendor_name}}</a>
													</h5>
												</div>
												{% if vendor.vendor_profile.pincode %}
												<address> <span>{{vendor.vendor_profile.state}}, {{vendor.vendor_profile.city}}, {{vendor.vendor_profile.pincode}}</address>
												{% endif %}
											</div>

											
										</div>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Choose From Most Popular Listing End -->

			<!-- Home Pages Elements End  -->
		</div>
		<!-- Main Section End -->
{% endblock content %}